theme: jekyll-theme-slate 
title:  MOIWA YAMA OF SAPPORO
description: How does it became TAs, What it is going to be in future
plugins: 
    - jemoji 
url: "https://kannyukiyou.github.io/" 
markdown: kramdown
